name: afu_hub_editor
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  amplify_flutter: ^1.0.0-next.7
  amplify_auth_cognito: ^1.0.0-next.0
  amplify_authenticator: ^1.0.0-next.5
  amplify_api: ^1.0.0-next.7
  amplify_datastore: ^1.0.0-next.7
  amplify_storage_s3: ^1.0.0-next.7
  get_it: ^7.2.0
  gap: ^2.0.0
  flutter_native_splash: ^2.2.19
  extra_alignments: ^1.0.0+1
  go_router: ^6.5.2
  intl: ^0.17.0
  image_picker: ^0.8.7+3
  riverpod_annotation: ^2.0.4
  flutter_animate: ^4.1.1+1
  cached_network_image: ^3.2.3
  dropdown_textfield: ^1.0.8
  flutter_localizations:

    sdk: flutter
  flutter_hooks: ^0.18.6
  hooks_riverpod: ^2.3.4
  path_provider: ^2.0.14


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
