name: afu_hub_editor
description: Editor app for afu_hub.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5

  amplify_flutter: ^1.0.0-next.8+1
  amplify_auth_cognito: ^1.0.0-next.8+1
  amplify_authenticator: ^1.0.0-next.5+2
  amplify_api: ^1.0.0-next.8+1
  amplify_datastore: ^1.1.0-supports-only-mobile
  amplify_storage_s3: ^1.0.0-next.8+1

  gap: ^3.0.0
  flutter_native_splash: ^2.2.19
  extra_alignments: ^1.0.0+1
  go_router: ^7.0.1
  intl: ^0.18.0
  image_picker: ^0.8.7+5
  riverpod_annotation: ^2.1.1

  flutter_animate: ^4.1.1+1
  cached_network_image: ^3.2.3
  dropdown_textfield: ^1.0.8
  flutter_localizations:
    sdk: flutter
  flutter_hooks: ^0.18.6
  hooks_riverpod: ^2.3.6
  path_provider: ^2.0.15
  image_picker_for_web: ^2.1.12
  get_it: ^7.6.0
  flutter_colorpicker: ^1.0.3



dev_dependencies:
  build_runner: ^2.4.4
  riverpod_generator: ^2.2.2
  riverpod_lint: ^1.3.1
  flutter_lints: ^2.0.1
  custom_lint: ^0.4.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/










  


  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
