name: On Website Deploy
"on":
  push:
    # (1)
    branches:
      - "main"
jobs:
  build_and_deploy_web:
    name: Build & Deploy Flutter to Web
    runs-on: ubuntu-latest
    # (2)
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: 🌍 Enable Web
        run: flutter config --enable-web

      - name: 📦 Get packages
        run: flutter pub get

      - name: 🏭 Build Web Application
        run: flutter build web --release

      # (3)
      - name: Make copy of artifacts
        run: |
          chmod u+x "${GITHUB_WORKSPACE}/createandcopytofolder.sh"
          bash "${GITHUB_WORKSPACE}/createandcopytofolder.sh"
      # (4)
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Commit the artifacts.
      # (5)
      - name: Hit a webhook
        run: |
          curl -X POST -d {} "https://webhooks.amplify.eu-central-1.amazonaws.com/prod/webhooks?id=fa5761b9-8739-44a1-8d1d-bce8b29002b4&token=qWdxvCMPonOGYYzu4jpMZHcJVhpItzwlDBnxhsbwLrc&operation=startbuild" -H "Content-Type:application/json"
